### ISSUE TITLE
Proposal to Purchase Luminotes.com Domain Name

### ISSUE THREAD

**Issue by Arthurpanck** [osborne6/luminotes#3]
Hello @osborne6 ,

I am reaching out to you today as the founder of a startup focused on note-taking and revision card creation. We have named our software "Luminotes,". I recently discovered that about a decade ago, you launched a project with the same name and acquired the corresponding domain name. In this context, I would like to discuss with you the possibility of purchasing the Luminotes.com domain name for our project.

You can contact me at this email address: pleemoressss@gmail.com
(It’s a secondary address, as I prefer not to expose my primary one on GitHub).

**Comment by osborne6** [comment]
I don't own the domain (I never have, as I was not the original owner of the company/project), I merely cloned the mercurial repository, converted it to git and have tried to update the code for personal purposes. I suggest performing a `whois` search on the domain to determine the current owner. A cursory glance at the wayback machine shows that the domain likely came into the possession of a domain parking site of some sort.

I wish you luck on your new startup and have a nice day.

**Comment by witten** [comment]
That's a great name for your software. :smile: I'm the original owner of the Luminotes domain, and I can confirm that the domain is currently held by a squatter. I suggest contacting them if you'd like to buy it.
